name: Upload assets

on:
  workflow_run:
    workflows: ["Build installer"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      run_id:
        description: "The ID of the workflow run to download artifacts from"
        required: true

permissions:
  contents: write
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Determine run_id
        id: set_run_id
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Triggered manually"
            echo "run_id=${{ github.event.inputs.run_id }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "Triggered by workflow_run"
            echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          else
            echo "Unknown trigger event: $GITHUB_EVENT_NAME"
            exit 1
          fi

      - name: Download artifacts
        run: |
          run_id=${{ steps.set_run_id.outputs.run_id }}
          mkdir -p artifacts
          gh run download $run_id -D artifacts/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename artifacts
        run: |
          for file in artifacts/*; do
            base=$(basename "$file")
            new="$base"
            new="${new/macos/osx}"
            new="${new/windows/win}"
      
            # Only move if the name actually changed
            if [ "$base" != "$new" ]; then
              mv "artifacts/$base" "artifacts/$new"
            fi
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Generate packages
        run: |
          pip install -r scripts/requirements.txt
          python scripts/package.py
          mv engine.zip artifacts/engine.zip
          mv locales.zip artifacts/locales.zip

      - name: Get latest release
        id: latest_release
        run: |
          latest=$(gh release list --limit 1 --json tagName,isPrerelease,publishedAt --jq '.[0].tagName')
          echo "Latest release tag: $latest"
          echo "release_tag=$latest" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to latest release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.latest_release.outputs.release_tag }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
