name: Upload assets

on:
  workflow_run:
    workflows: ["Build installer"]
    types:
      - completed

permissions:
  contents: write
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.inputs.upload_assets != 'false' }}

    steps:
      - name: Download artifacts
        run: |
          run_id=${{ github.event.workflow_run.id }}
          mkdir -p artifacts
          gh run download $run_id -D artifacts/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename artifacts
        run: |
          for file in artifacts/*; do
            new=$(basename "$file")
            new="${new/macos/osx}"
            new="${new/windows/win}"
            mv "$file" "artifacts/$new"
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Generate packages
        run: |
          pip install -r scripts/requirements.txt
          python scripts/package.py
          mv engine.zip artifacts/engine.zip
          mv locales.zip artifacts/locales.zip

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
